// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/collection": {
    params: {};
  };
  "/upload": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/collection" | "/upload" | "/login" | "/home" | "/*";
  };
  "routes/[collection]._index.jsx": {
    id: "routes/[collection]._index";
    page: "/collection";
  };
  "routes/[upload]._index.jsx": {
    id: "routes/[upload]._index";
    page: "/upload";
  };
  "routes/[login]._index.jsx": {
    id: "routes/[login]._index";
    page: "/login";
  };
  "routes/[home]._index.jsx": {
    id: "routes/[home]._index";
    page: "/home";
  };
  "routes/[404]._index.jsx": {
    id: "routes/[404]._index";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/[collection]._index": typeof import("./app/routes/[collection]._index.jsx");
  "routes/[upload]._index": typeof import("./app/routes/[upload]._index.jsx");
  "routes/[login]._index": typeof import("./app/routes/[login]._index.jsx");
  "routes/[home]._index": typeof import("./app/routes/[home]._index.jsx");
  "routes/[404]._index": typeof import("./app/routes/[404]._index.jsx");
};